/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa.Ventanas;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import puntodeventa.PuntoDeVenta;

public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        PuntoDeVenta pdv = new PuntoDeVenta();
        pdv.setFavicon(this);
        pdv.setPosition(this);
        
        //Botones
        btn_empleados.setIcon(pdv.setIcono("/img/empleados.png",btn_empleados));
        btn_clientes.setIcon(pdv.setIcono("/img/clientes.png",btn_clientes));
        btn_pedidos.setIcon(pdv.setIcono("/img/pedidos.png",btn_pedidos));
        btn_pagos.setIcon(pdv.setIcono("/img/pagos.png",btn_pagos));
        btn_detalles.setIcon(pdv.setIcono("/img/detalles.png",btn_pagos));
        btn_oficinas.setIcon(pdv.setIcono("/img/oficinas.png",btn_pagos));
        btn_productos.setIcon(pdv.setIcono("/img/productos.png",btn_pagos));
        btn_lin_productos.setIcon(pdv.setIcono("/img/lineas_producto.png",btn_pagos));
        
        btn_empleados.setBackground(Color.white);
        btn_clientes.setBackground(Color.white);
        btn_pedidos.setBackground(Color.white);
        btn_pagos.setBackground(Color.white);
        btn_detalles.setBackground(Color.white);
        btn_oficinas.setBackground(Color.white);
        btn_productos.setBackground(Color.white);
        btn_lin_productos.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_clientes = new javax.swing.JButton();
        btn_empleados = new javax.swing.JButton();
        btn_pedidos = new javax.swing.JButton();
        btn_pagos = new javax.swing.JButton();
        btnName_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_detalles = new javax.swing.JButton();
        btn_lin_productos = new javax.swing.JButton();
        btn_oficinas = new javax.swing.JButton();
        btn_productos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Punto de Venta");
        setResizable(false);

        btn_clientes.setToolTipText("");
        btn_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clientes.setFocusable(false);
        btn_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clientesMouseExited(evt);
            }
        });
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });

        btn_empleados.setToolTipText("");
        btn_empleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_empleados.setFocusable(false);
        btn_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_empleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_empleadosMouseExited(evt);
            }
        });
        btn_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empleadosActionPerformed(evt);
            }
        });

        btn_pedidos.setToolTipText("");
        btn_pedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pedidos.setFocusable(false);
        btn_pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pedidosMouseExited(evt);
            }
        });
        btn_pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pedidosActionPerformed(evt);
            }
        });

        btn_pagos.setToolTipText("");
        btn_pagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pagos.setFocusable(false);
        btn_pagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pagosMouseExited(evt);
            }
        });
        btn_pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagosActionPerformed(evt);
            }
        });

        btnName_label.setBackground(new java.awt.Color(51, 51, 51));
        btnName_label.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnName_label.setForeground(new java.awt.Color(255, 255, 255));
        btnName_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnName_label.setText("SELECCIONE UNA OPCIÓN");
        btnName_label.setOpaque(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdv_logo.png"))); // NOI18N

        btn_detalles.setToolTipText("");
        btn_detalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_detalles.setFocusable(false);
        btn_detalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_detallesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_detallesMouseExited(evt);
            }
        });
        btn_detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detallesActionPerformed(evt);
            }
        });

        btn_lin_productos.setToolTipText("");
        btn_lin_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_lin_productos.setFocusable(false);
        btn_lin_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lin_productosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lin_productosMouseExited(evt);
            }
        });
        btn_lin_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lin_productosActionPerformed(evt);
            }
        });

        btn_oficinas.setToolTipText("");
        btn_oficinas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_oficinas.setFocusable(false);
        btn_oficinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_oficinasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_oficinasMouseExited(evt);
            }
        });
        btn_oficinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oficinasActionPerformed(evt);
            }
        });

        btn_productos.setToolTipText("");
        btn_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_productos.setFocusable(false);
        btn_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_productosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_productosMouseExited(evt);
            }
        });
        btn_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnName_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_oficinas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_lin_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_detalles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnName_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_oficinas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_detalles, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_lin_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_pedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        this.dispose();
        try {
            new Clientes().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void btn_pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pedidosActionPerformed
        this.dispose();
        try {
            new Pedidos().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_pedidosActionPerformed

    private void btn_pagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagosActionPerformed
        this.dispose();
        try {
            new Pagos().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_pagosActionPerformed

    private void btn_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empleadosActionPerformed
        this.dispose();
        try {
            new Empleados().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_empleadosActionPerformed

    private void btn_empleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadosMouseEntered
        btnName_label.setText("Ver Empleados".toUpperCase());
    }//GEN-LAST:event_btn_empleadosMouseEntered

    private void btn_empleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empleadosMouseExited
        btnName_label.setText("Seleccione una opción".toUpperCase());
    }//GEN-LAST:event_btn_empleadosMouseExited

    private void btn_clientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientesMouseEntered
        btnName_label.setText("Ver Clientes".toUpperCase());
    }//GEN-LAST:event_btn_clientesMouseEntered

    private void btn_clientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientesMouseExited
        btnName_label.setText("Seleccione una opción".toUpperCase());
    }//GEN-LAST:event_btn_clientesMouseExited

    private void btn_pedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pedidosMouseEntered
        btnName_label.setText("Ver Pedidos".toUpperCase());
    }//GEN-LAST:event_btn_pedidosMouseEntered

    private void btn_pedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pedidosMouseExited
        btnName_label.setText("Seleccione una opción".toUpperCase());
    }//GEN-LAST:event_btn_pedidosMouseExited

    private void btn_pagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pagosMouseEntered
        btnName_label.setText("Ver Pagos Realizados".toUpperCase());
    }//GEN-LAST:event_btn_pagosMouseEntered

    private void btn_pagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pagosMouseExited
        btnName_label.setText("Seleccione una opción".toUpperCase());
    }//GEN-LAST:event_btn_pagosMouseExited

    private void btn_detallesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detallesMouseEntered
        btnName_label.setText("Ver Detalles de Pedidos".toUpperCase());
    }//GEN-LAST:event_btn_detallesMouseEntered

    private void btn_detallesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_detallesMouseExited
        btnName_label.setText("Seleccione una opción".toUpperCase());
    }//GEN-LAST:event_btn_detallesMouseExited

    private void btn_detallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detallesActionPerformed
        this.dispose();
        try {
            new Detalles().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_detallesActionPerformed

    private void btn_lin_productosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lin_productosMouseEntered
        btnName_label.setText("Ver Lineas de Producto".toUpperCase());
    }//GEN-LAST:event_btn_lin_productosMouseEntered

    private void btn_lin_productosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lin_productosMouseExited
        btnName_label.setText("Seleccione una opción".toUpperCase());
    }//GEN-LAST:event_btn_lin_productosMouseExited

    private void btn_lin_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lin_productosActionPerformed
        this.dispose();
        try {
            new Lineas().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_lin_productosActionPerformed

    private void btn_oficinasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_oficinasMouseEntered
        btnName_label.setText("Ver Oficinas".toUpperCase());
    }//GEN-LAST:event_btn_oficinasMouseEntered

    private void btn_oficinasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_oficinasMouseExited
        btnName_label.setText("Seleccione una opción".toUpperCase());
    }//GEN-LAST:event_btn_oficinasMouseExited

    private void btn_oficinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oficinasActionPerformed
        this.dispose();
        try {
            new Oficinas().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_oficinasActionPerformed

    private void btn_productosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productosMouseEntered
        btnName_label.setText("Ver Productos".toUpperCase());
    }//GEN-LAST:event_btn_productosMouseEntered

    private void btn_productosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productosMouseExited
        btnName_label.setText("Seleccione una opción".toUpperCase());
    }//GEN-LAST:event_btn_productosMouseExited

    private void btn_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productosActionPerformed
        this.dispose();
        try {
            new Productos().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_productosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnName_label;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_detalles;
    private javax.swing.JButton btn_empleados;
    private javax.swing.JButton btn_lin_productos;
    private javax.swing.JButton btn_oficinas;
    private javax.swing.JButton btn_pagos;
    private javax.swing.JButton btn_pedidos;
    private javax.swing.JButton btn_productos;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
