/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa.Ventanas;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import puntodeventa.Conexiones.LineasDB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import puntodeventa.PuntoDeVenta;

public class Lineas extends javax.swing.JFrame {
    private final LineasDB base = new LineasDB();
    private final PuntoDeVenta pdv = new PuntoDeVenta();

    public Lineas() throws SQLException {
        initComponents();
        
        contenedor.removeAll();
        
        pdv.setFavicon(this);
        pdv.setPosition(this);
        pdv.setEnterButton(this, btn_buscar);
        
        btn_agregar.setIcon(pdv.setIcono("/img/r_agregar.png",btn_agregar));
        btn_editar.setIcon(pdv.setIcono("/img/r_editar.png",btn_editar));
        btn_eliminar.setIcon(pdv.setIcono("/img/r_eliminar.png",btn_eliminar));
        
        tabla_lineas.setModel(base.getLineas());
        
        btn_delete.setEnabled(false);
    }
    
    private byte[] imgToBytes(String imagen){
        try{
            byte[] img_bytes = null;
            File image = new File(imagen);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum = fis.read(buf)) != -1;){
                bos.write(buf, 0, readNum);
            }
            
            img_bytes = bos.toByteArray();
            return img_bytes;
        }
        catch(Exception e){
            return null;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_lineas = new javax.swing.JTable();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        contenedor = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        txt_delete_lin = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_delete_tdesc = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_delete_hdesc = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        txt_edit_lin = new javax.swing.JTextField();
        txt_edit_img = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_edit_tdesc = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_edit_hdesc = new javax.swing.JTextArea();
        btn_edit_ele = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_add_img = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_add_lin = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_add_tdesc = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_add_hdesc = new javax.swing.JTextArea();
        btn_add_ele = new javax.swing.JButton();
        btn_borrar_img = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SYSPDV - Lineas");
        setResizable(false);
        setSize(new java.awt.Dimension(529, 332));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabla_lineas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_lineas.setEditingColumn(0);
        tabla_lineas.setEditingRow(0);
        tabla_lineas.setFillsViewportHeight(true);
        tabla_lineas.setRowHeight(60);
        tabla_lineas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_lineasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_lineas);

        txt_buscar.setText("Número");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar por linea de producto");

        btn_agregar.setToolTipText("Agregar");
        btn_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agregar.setFocusable(false);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_editar.setToolTipText("Editar");
        btn_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editar.setFocusable(false);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_eliminar.setToolTipText("Eliminar");
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.setFocusable(false);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        contenedor.setLayout(new java.awt.CardLayout());

        jLabel4.setText("Borrar detalle | (Seleccione un detalle de la lista para autocompletar los datos)");

        btn_delete.setText("Borrar");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        txt_delete_lin.setEditable(false);
        txt_delete_lin.setText("Linea");

        txt_delete_tdesc.setEditable(false);
        txt_delete_tdesc.setColumns(3);
        txt_delete_tdesc.setRows(5);
        txt_delete_tdesc.setText("Descripcion textual");
        jScrollPane6.setViewportView(txt_delete_tdesc);

        txt_delete_hdesc.setEditable(false);
        txt_delete_hdesc.setColumns(3);
        txt_delete_hdesc.setRows(5);
        txt_delete_hdesc.setText("Descripcion html");
        jScrollPane7.setViewportView(txt_delete_hdesc);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_delete_lin, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(183, 235, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_delete_lin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        contenedor.add(jPanel3, "card4");

        jLabel3.setText("Editar detalle | (Seleccione un detalle de la lista para autocompletar los datos)");

        btn_edit.setText("Grabar");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        txt_edit_lin.setEditable(false);
        txt_edit_lin.setText("Linea");

        txt_edit_img.setEditable(false);

        txt_edit_tdesc.setColumns(20);
        txt_edit_tdesc.setRows(5);
        txt_edit_tdesc.setText("Descripcion textual");
        jScrollPane4.setViewportView(txt_edit_tdesc);

        txt_edit_hdesc.setColumns(20);
        txt_edit_hdesc.setRows(5);
        txt_edit_hdesc.setText("Descripcion html");
        jScrollPane5.setViewportView(txt_edit_hdesc);

        btn_edit_ele.setText("Elegir imagen");
        btn_edit_ele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_eleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txt_edit_lin, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_edit_img, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_edit_ele)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(164, 164, 164))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_edit_lin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_edit_img, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit_ele))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        contenedor.add(jPanel2, "card3");

        txt_add_img.setEditable(false);

        btn_add.setText("Agregar");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jLabel1.setText("Agregar nuevo detalle");

        txt_add_lin.setText("Linea");

        txt_add_tdesc.setColumns(20);
        txt_add_tdesc.setRows(5);
        txt_add_tdesc.setText("Descripcion textual");
        jScrollPane2.setViewportView(txt_add_tdesc);

        txt_add_hdesc.setColumns(20);
        txt_add_hdesc.setRows(5);
        txt_add_hdesc.setText("Descripcion html");
        jScrollPane3.setViewportView(txt_add_hdesc);

        btn_add_ele.setText("Elegir imagen");
        btn_add_ele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_eleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_add_lin, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_add_img, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_add_ele)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(158, 158, 158))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_add_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_add_lin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_add_ele)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contenedor.add(jPanel1, "card2");

        btn_borrar_img.setText("Borrar imagen");
        btn_borrar_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrar_imgActionPerformed(evt);
            }
        });

        jLabel5.setText("Borrar imagen de linea");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_buscar))
                                .addComponent(jLabel2))
                            .addGap(83, 83, 83)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(btn_borrar_img))))
                    .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_borrar_img))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Inicio ventana = new Inicio();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        try {
            if(txt_buscar.getText().length() == 0){
                tabla_lineas.setModel(base.getLineas());
            }else{
                tabla_lineas.setModel(base.getLineas(txt_buscar.getText()));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Lineas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        pdv.switchPanels(jPanel1, contenedor);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        pdv.switchPanels(jPanel2, contenedor);
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        pdv.switchPanels(jPanel3, contenedor);
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        String linea = txt_add_lin.getText();
        String desc_texto = txt_add_tdesc.getText();
        String desc_html = txt_add_hdesc.getText();
        String imagen = txt_add_img.getText();

        try {
            if(imagen.length() > 0){
              byte[] img_bytes = imgToBytes(imagen);
              if(img_bytes == null){
                JOptionPane.showMessageDialog(null, "Error al cargar la imagen!");
              }else{
                base.addLinea(linea, desc_texto, desc_html, img_bytes);  
              }  
            }else{
                base.addLinea(linea, desc_texto, desc_html);
            }
 
            tabla_lineas.setModel(base.getLineas());
            txt_add_img.setText(null);
        } catch (Exception e) {
            Logger.getLogger(Lineas.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void tabla_lineasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_lineasMouseClicked
        if(tabla_lineas.getSelectedRow() != -1){
                btn_delete.setEnabled(true);
        }
        int row = tabla_lineas.getSelectedRow(); //Obtener fila seleccionada
         
        //Cargar datos en panel editar
        txt_edit_lin.setText(tabla_lineas.getValueAt(row, 0).toString());
        txt_edit_tdesc.setText(tabla_lineas.getValueAt(row, 1) == null ? "" : tabla_lineas.getValueAt(row, 1).toString());
        txt_edit_hdesc.setText(tabla_lineas.getValueAt(row, 2) == null ? "" : tabla_lineas.getValueAt(row, 2).toString());
        
        //Cargar datos en el panel borrar
        txt_delete_lin.setText(tabla_lineas.getValueAt(row, 0).toString());
        txt_delete_tdesc.setText(tabla_lineas.getValueAt(row, 1) == null ? "" : tabla_lineas.getValueAt(row, 1).toString());
        txt_delete_hdesc.setText(tabla_lineas.getValueAt(row, 2) == null ? "" : tabla_lineas.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tabla_lineasMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        String numero = txt_delete_lin.getText();
        
        int opc = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar el detalle?", "Eliminando detalle", JOptionPane.YES_NO_OPTION);
        
        if(opc == JOptionPane.YES_OPTION){
           try {
            base.deleteLinea(numero);
            tabla_lineas.setModel(base.getLineas());
            } catch (SQLException ex) {
            Logger.getLogger(Lineas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        String linea = txt_edit_lin.getText();
        String desc_texto = txt_edit_tdesc.getText();
        String desc_html = txt_edit_hdesc.getText();
        String imagen = txt_edit_img.getText();
        
        try {
            if(imagen.length() > 0){
              byte[] img_bytes = imgToBytes(imagen);
              if(img_bytes == null){
                JOptionPane.showMessageDialog(null, "Error al cargar la imagen!");
              }else{
                base.editLinea(linea, desc_texto, desc_html, img_bytes);  
              }  
            }else{
                base.editLinea(linea, desc_texto, desc_html);
            }
 
            tabla_lineas.setModel(base.getLineas());
            txt_edit_img.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(Lineas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_add_eleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_eleActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f == null ? "" : f.getAbsolutePath();
        txt_add_img.setText(filename);
    }//GEN-LAST:event_btn_add_eleActionPerformed

    private void btn_edit_eleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_eleActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f == null ? "" : f.getAbsolutePath();
        txt_edit_img.setText(filename);
    }//GEN-LAST:event_btn_edit_eleActionPerformed

    private void btn_borrar_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrar_imgActionPerformed
        if(tabla_lineas.getSelectedRow() != -1){
          try {
            int row = tabla_lineas.getSelectedRow();//Obtener fila seleccionada
            if(tabla_lineas.getValueAt(row, 3) != null){
                base.editLinea(tabla_lineas.getValueAt(row, 0).toString());
            }else{
                JOptionPane.showMessageDialog(null, "La linea seleccionada no tiene una imagen!", "Error eliminando la imagen", 1);
            }
            tabla_lineas.setModel(base.getLineas());
            } catch (Exception e) {
                Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, e);
            }  
        }else{
         JOptionPane.showMessageDialog(null, "Debe seleccionar una linea!");   
        }
    }//GEN-LAST:event_btn_borrar_imgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Lineas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Lineas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_add_ele;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_borrar_img;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_edit_ele;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLayeredPane contenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tabla_lineas;
    private javax.swing.JTextArea txt_add_hdesc;
    private javax.swing.JTextField txt_add_img;
    private javax.swing.JTextField txt_add_lin;
    private javax.swing.JTextArea txt_add_tdesc;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextArea txt_delete_hdesc;
    private javax.swing.JTextField txt_delete_lin;
    private javax.swing.JTextArea txt_delete_tdesc;
    private javax.swing.JTextArea txt_edit_hdesc;
    private javax.swing.JTextField txt_edit_img;
    private javax.swing.JTextField txt_edit_lin;
    private javax.swing.JTextArea txt_edit_tdesc;
    // End of variables declaration//GEN-END:variables
}
